apiVersion: v1
kind: Service
metadata:
  name: mongo-0
  namespace: mybox
  labels:
    app: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1
  namespace: mybox
  labels:
    app: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongo-1

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-2
  namespace: mybox
  labels:
    app: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongo-2