apiVersion: v1
kind: Service
metadata:
  name: mongodb-nfs
  namespace: mybox
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
  selector:
    app: mongodb-nfs
