apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
 name: mongo-nfs-pvc
 namespace: mybox
spec:
  accessModes: 
   - ReadWriteOnce
  resources: 
   requests:
    storage: 400m
  storageClassName: nfs-client